-- =============================================================
-- Modelo físico inicial — Sprint 1 (Plataforma de Reservas)
-- PostgreSQL 15+ (Supabase). Generado a partir del mapeo JPA
-- (hibernate ddl-auto=update en local; validate en la nube).
-- Las credenciales viven en auth.users (Supabase); aquí solo
-- perfiles de negocio y soporte de autenticación.
-- =============================================================

-- Perfil de cliente (HU-001). id = auth.users.id
create table if not exists clients (
    id                   uuid         not null,
    full_name            varchar(120) not null,
    document             varchar(30)  not null,
    birth_date           date         not null,
    email                varchar(160) not null,
    phone                varchar(20)  not null,
    city                 varchar(80)  not null,
    notification_channel varchar(20)  not null, -- EMAIL | SMS | WHATSAPP
    status               varchar(30)  not null, -- PENDING_VERIFICATION | ACTIVE | SUSPENDED
    created_at           timestamp(6) not null,
    updated_at           timestamp(6) not null,
    primary key (id),
    constraint uk_clients_email unique (email),
    constraint uk_clients_document unique (document)
);

-- Intentos de login para la política de bloqueo (HU-021)
create table if not exists login_attempts (
    id           bigint generated by default as identity,
    email        varchar(160) not null,
    success      boolean      not null,
    attempted_at timestamp(6) not null,
    primary key (id)
);

create index if not exists ix_login_attempts_email_time
    on login_attempts (email, attempted_at);

-- =============================================================
-- Restricciones de integridad adicionales sobre lo generado
-- por Hibernate (se aplican una vez creado el esquema):
-- =============================================================

alter table clients drop constraint if exists ck_clients_status;
alter table clients add constraint ck_clients_status
    check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED'));

alter table clients drop constraint if exists ck_clients_notification_channel;
alter table clients add constraint ck_clients_notification_channel
    check (notification_channel in ('EMAIL', 'SMS', 'WHATSAPP'));

alter table clients drop constraint if exists ck_clients_adult;
alter table clients add constraint ck_clients_adult
    check (birth_date <= current_date - interval '18 years');

comment on table clients is 'Perfil de cliente (HU-001); id = auth.users.id de Supabase';
comment on table login_attempts is 'Auditoría de intentos de login para bloqueo temporal (HU-021)';
